service: convert-file

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: ap-southeast-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  hello:
    memorySize: 256
    timeout: 120
    handler: index.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline

custom:
  secrets: ${file(secrets.json)}
