name: Deploy Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: sed env
        run: |
          export VAULT_ADDR='http://127.0.0.1:8200'
          vault login ${{ secrets.VAULT_TOKEN }}
          vault kv get -field=RENDER_ENV_FILE secret/stg > .env
      - run: npm install
      - name: Deploy render
        run: |
          rsync -hrzog --chown centos:centos --delete --bwlimit=8192 --timeout=600 --rsync-path="sudo rsync" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ centos@172.31.16.157:/srv/husble-render/
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@172.31.16.157 " cd /srv/husble-render/ && pm2 restart husble-render"
        shell: bash
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
